version: '2'
services:
  open-falcon:
    build: .
    ports:
      - "8433:8433"
      - "6030:6030"
      - "5050:5050"
      - "1234:1234"
      - "8081:8081"
      - "6060:6060"
      - "5090:5090"
      - "9912:9912"
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      DOCKER_HOST_IP: 192.168.0.101
    volumes:
      - /vagrant/open-falcon/cfg:/home/open-falcon/cfg
      - /vagrant/open-falcon/config:/home/open-falcon/config
      - /home/open-falcon/data:/home/open-falcon/data
      - /home/open-falcon/logs:/home/open-falcon/logs
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - /vagrant/open-falcon/sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"